spring:
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/home_financial_manager
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

secret.key: chavemaissecretadouniversointeiro33x
token.life: 3600000

api:
  mailer:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    tls: true
    username: 143364ce966164
    password: 2528685cf96b73