spring:
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/home_financial_manager
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

swagger:
  enabled: true